import { ValueNode } from './types';

export const POLE_MAP: Record<number, number> = {
  1: 0,
  2: 36,
  3: 72,
  4: 108,
  5: 144,
  6: 180,
  7: 216,
  8: 252,
  9: 288,
  10: 324
};

export const INITIAL_VALUES: ValueNode[] = [
  {
    id: "aut-01",
    label: "Autonomy",
    pole: 1,
    angle: 0,
    simpleDefinition: "Being in control of your own life and making your own choices.",
    studentDefinition: "Having the power to think for yourself and choose your own path without everyone else telling you what to do.",
    status: 'unseen',
    elo: 1200,
    wins: [],
    losses: []
  },
  {
    id: "cur-01",
    label: "Curiosity",
    pole: 1,
    angle: 0,
    simpleDefinition: "Having a strong desire to learn, explore, and understand how things work.",
    studentDefinition: "Being the person who always asks \"why?\" because you really want to figure out how the world works.",
    status: 'unseen',
    elo: 1200,
    wins: [],
    losses: []
  },
  {
    id: "cre-01",
    label: "Creativity",
    pole: 1,
    angle: 0,
    simpleDefinition: "Using your imagination to make something new or solve problems in unique ways.",
    studentDefinition: "Coming up with cool, original ideas—whether it's through art, coding, or finding a new way to finish a task.",
    status: 'unseen',
    elo: 1200,
    wins: [],
    losses: []
  },
  {
    id: "ind-01",
    label: "Independence",
    pole: 1,
    angle: 0,
    simpleDefinition: "Relying on yourself rather than depending on others for help or direction.",
    studentDefinition: "Doing things on your own and trusting yourself to get the job done without needing someone to hold your hand.",
    status: 'unseen',
    elo: 1200,
    wins: [],
    losses: []
  },
  {
    id: "cho-01",
    label: "Choice",
    pole: 1,
    angle: 0,
    simpleDefinition: "Having the freedom to pick between different options based on what you want.",
    studentDefinition: "Having the right to pick what you want to do, like choosing your own subjects, hobbies, or friends.",
    status: 'unseen',
    elo: 1200,
    wins: [],
    losses: []
  },
  {
    id: "sre-01",
    label: "Self-Reliance",
    pole: 1,
    angle: 0,
    simpleDefinition: "Trusting your own powers and abilities to handle life’s challenges.",
    studentDefinition: "Knowing that even if things get tough, you have the skills to take care of yourself and figure it out.",
    status: 'unseen',
    elo: 1200,
    wins: [],
    losses: []
  },
  {
    id: "adv-01",
    label: "Adventure",
    pole: 2,
    angle: 36,
    simpleDefinition: "Seeking out new, exciting, and sometimes challenging experiences.",
    studentDefinition: "Going outside your comfort zone to try something new, like traveling to a new place or starting a bold project.",
    status: 'unseen',
    elo: 1200,
    wins: [],
    losses: []
  },
  {
    id: "vit-01",
    label: "Vitality",
    pole: 2,
    angle: 36,
    simpleDefinition: "Feeling full of energy, life, and spirit in everything you do.",
    studentDefinition: "Having that \"get up and go\" energy that makes you feel excited and ready to take on the day.",
    status: 'unseen',
    elo: 1200,
    wins: [],
    losses: []
  },
  {
    id: "ris-01",
    label: "Risk-Taking",
    pole: 2,
    angle: 36,
    simpleDefinition: "Being willing to try something even if you aren't 100% sure it will work out.",
    studentDefinition: "Taking a chance on something new, even if you’re a little nervous that it might not go perfectly.",
    status: 'unseen',
    elo: 1200,
    wins: [],
    losses: []
  },
  {
    id: "spo-01",
    label: "Spontaneity",
    pole: 2,
    angle: 36,
    simpleDefinition: "Acting on a sudden impulse or idea rather than following a strict plan.",
    studentDefinition: "Being okay with changing plans at the last minute because a fun, new idea popped up.",
    status: 'unseen',
    elo: 1200,
    wins: [],
    losses: []
  },
  {
    id: "nov-01",
    label: "Novelty",
    pole: 2,
    angle: 36,
    simpleDefinition: "Seeking out things that are new, different, or unusual.",
    studentDefinition: "Loving the feeling of trying a brand-new game, food, or activity for the first time just because it’s different.",
    status: 'unseen',
    elo: 1200,
    wins: [],
    losses: []
  },
  {
    id: "exc-01",
    label: "Excitement",
    pole: 2,
    angle: 36,
    simpleDefinition: "Searching for activities that make you feel thrilled and energized.",
    studentDefinition: "Looking for that \"rush\" you get when you’re doing something fun, fast, or totally awesome.",
    status: 'unseen',
    elo: 1200,
    wins: [],
    losses: []
  },
  {
    id: "ple-01",
    label: "Pleasure",
    pole: 3,
    angle: 72,
    simpleDefinition: "Enjoying the things that make you feel good and happy in the moment.",
    studentDefinition: "Doing things just because they make you smile and feel great, like eating your favorite meal.",
    status: 'unseen',
    elo: 1200,
    wins: [],
    losses: []
  },
  {
    id: "com-01",
    label: "Comfort",
    pole: 3,
    angle: 72,
    simpleDefinition: "Having a life that is physically and mentally easy, safe, and relaxed.",
    studentDefinition: "That cozy feeling of being in a place where you can totally relax and not worry about anything.",
    status: 'unseen',
    elo: 1200,
    wins: [],
    losses: []
  },
  {
    id: "lei-01",
    label: "Leisure",
    pole: 3,
    angle: 72,
    simpleDefinition: "Taking time away from work or responsibilities to rest and play.",
    studentDefinition: "Making sure you have \"me time\" to play video games, hang out, or just chill out after school.",
    status: 'unseen',
    elo: 1200,
    wins: [],
    losses: []
  },
  {
    id: "gra-01",
    label: "Gratification",
    pole: 3,
    angle: 72,
    simpleDefinition: "Getting what you want or need and feeling satisfied because of it.",
    studentDefinition: "That \"yes!\" feeling when you finally get the thing you’ve been wanting for a long time.",
    status: 'unseen',
    elo: 1200,
    wins: [],
    losses: []
  },
  {
    id: "joy-01",
    label: "Joy",
    pole: 3,
    angle: 72,
    simpleDefinition: "A deep feeling of great happiness and satisfaction.",
    studentDefinition: "That big, awesome feeling of being genuinely happy about your life and the people in it.",
    status: 'unseen',
    elo: 1200,
    wins: [],
    losses: []
  },
  {
    id: "sen-01",
    label: "Sensuality",
    pole: 3,
    angle: 72,
    simpleDefinition: "Appreciating beauty and physical feelings through your senses.",
    studentDefinition: "Noticing and enjoying the little things, like the way a song sounds or how a sunset looks.",
    status: 'unseen',
    elo: 1200,
    wins: [],
    losses: []
  },
  {
    id: "suc-01",
    label: "Success",
    pole: 4,
    angle: 108,
    simpleDefinition: "Reaching the goals you set for yourself and doing well in what you do.",
    studentDefinition: "Setting a goal—like passing a hard test or winning a game—and actually making it happen.",
    status: 'unseen',
    elo: 1200,
    wins: [],
    losses: []
  },
  {
    id: "cmp-01",
    label: "Competence",
    pole: 4,
    angle: 108,
    simpleDefinition: "Being good at what you do and having the skills to handle tasks well.",
    studentDefinition: "Knowing your stuff and being the person people can count on because you’re good at what you do.",
    status: 'unseen',
    elo: 1200,
    wins: [],
    losses: []
  },
  {
    id: "amb-01",
    label: "Ambition",
    pole: 4,
    angle: 108,
    simpleDefinition: "Having a strong desire to achieve great things and work hard for them.",
    studentDefinition: "Having big dreams for your future and being willing to put in the work to get there.",
    status: 'unseen',
    elo: 1200,
    wins: [],
    losses: []
  },
  {
    id: "mas-01",
    label: "Mastery",
    pole: 4,
    angle: 108,
    simpleDefinition: "Becoming an expert at something through practice and dedication.",
    studentDefinition: "Practicing something—like a sport or an instrument—until you are one of the best at it.",
    status: 'unseen',
    elo: 1200,
    wins: [],
    losses: []
  },
  {
    id: "cap-01",
    label: "Capability",
    pole: 4,
    angle: 108,
    simpleDefinition: "Having the tools, skills, and power to produce a specific result.",
    studentDefinition: "Knowing that you have what it takes to finish a project or solve a problem on your own.",
    status: 'unseen',
    elo: 1200,
    wins: [],
    losses: []
  },
  {
    id: "imp-01",
    label: "Impact",
    pole: 4,
    angle: 108,
    simpleDefinition: "Making a clear and positive difference through your actions.",
    studentDefinition: "Seeing that what you did actually changed something for the better in your school or community.",
    status: 'unseen',
    elo: 1200,
    wins: [],
    losses: []
  },
  {
    id: "aut-02",
    label: "Authority",
    pole: 5,
    angle: 144,
    simpleDefinition: "Having the power to give orders, make decisions, and lead others.",
    studentDefinition: "Being the one in charge who makes the big decisions and makes sure everyone stays on track.",
    status: 'unseen',
    elo: 1200,
    wins: [],
    losses: []
  },
  {
    id: "wea-01",
    label: "Wealth",
    pole: 5,
    angle: 144,
    simpleDefinition: "Having plenty of money, possessions, or valuable resources.",
    studentDefinition: "Having enough money and \"stuff\" to live the life you want and take care of your needs.",
    status: 'unseen',
    elo: 1200,
    wins: [],
    losses: []
  },
  {
    id: "sta-01",
    label: "Social Status",
    pole: 5,
    angle: 144,
    simpleDefinition: "Being respected or admired by other people in your community.",
    studentDefinition: "Being someone that others look up to or think is important because of what you’ve done.",
    status: 'unseen',
    elo: 1200,
    wins: [],
    losses: []
  },
  {
    id: "inf-01",
    label: "Influence",
    pole: 5,
    angle: 144,
    simpleDefinition: "Having the power to change how other people think or act.",
    studentDefinition: "Having the kind of voice where people actually listen to your ideas and follow your lead.",
    status: 'unseen',
    elo: 1200,
    wins: [],
    losses: []
  },
  {
    id: "lea-01",
    label: "Leadership",
    pole: 5,
    angle: 144,
    simpleDefinition: "Guiding a group of people toward a common goal or vision.",
    studentDefinition: "Being the captain of the team or the leader of a group project who helps everyone work together.",
    status: 'unseen',
    elo: 1200,
    wins: [],
    losses: []
  },
  {
    id: "rec-01",
    label: "Recognition",
    pole: 5,
    angle: 144,
    simpleDefinition: "Being noticed and praised by others for your hard work or success.",
    studentDefinition: "Getting a \"good job!\" or an award that shows people noticed how hard you worked.",
    status: 'unseen',
    elo: 1200,
    wins: [],
    losses: []
  },
  {
    id: "saf-01",
    label: "Safety",
    pole: 6,
    angle: 180,
    simpleDefinition: "Being in a situation where you are protected from danger or harm.",
    studentDefinition: "Feeling like you’re in a place where nothing bad is going to happen to you.",
    status: 'unseen',
    elo: 1200,
    wins: [],
    losses: []
  },
  {
    id: "stb-01",
    label: "Stability",
    pole: 6,
    angle: 180,
    simpleDefinition: "Having a life that is steady, predictable, and not likely to change suddenly.",
    studentDefinition: "Knowing that your life is solid and that you can count on things staying mostly the same.",
    status: 'unseen',
    elo: 1200,
    wins: [],
    losses: []
  },
  {
    id: "fse-01",
    label: "Financial Security",
    pole: 6,
    angle: 180,
    simpleDefinition: "Having enough money to cover your needs without worrying about the future.",
    studentDefinition: "Knowing that you (or your family) have enough money to pay for the things you need, like food and a home.",
    status: 'unseen',
    elo: 1200,
    wins: [],
    losses: []
  },
  {
    id: "fam-01",
    label: "Family Security",
    pole: 6,
    angle: 180,
    simpleDefinition: "Making sure the people you live with are safe, healthy, and protected.",
    studentDefinition: "Looking out for your parents, siblings, and relatives to make sure everyone at home is okay.",
    status: 'unseen',
    elo: 1200,
    wins: [],
    losses: []
  },
  {
    id: "hea-01",
    label: "Health",
    pole: 6,
    angle: 180,
    simpleDefinition: "Taking care of your body and mind so you feel strong and well.",
    studentDefinition: "Keeping yourself fit, eating right, and making sure your mind feels happy and healthy too.",
    status: 'unseen',
    elo: 1200,
    wins: [],
    losses: []
  },
  {
    id: "rel-01",
    label: "Reliability",
    pole: 6,
    angle: 180,
    simpleDefinition: "Being a person that others can always count on to do what you say.",
    studentDefinition: "Being the friend who always shows up when they say they will and never lets people down.",
    status: 'unseen',
    elo: 1200,
    wins: [],
    losses: []
  },
  {
    id: "sdi-01",
    label: "Self-Discipline",
    pole: 7,
    angle: 216,
    simpleDefinition: "Controlling your own feelings and actions to reach a goal.",
    studentDefinition: "Being able to stay focused on your homework even when you really want to play games instead.",
    status: 'unseen',
    elo: 1200,
    wins: [],
    losses: []
  },
  {
    id: "pol-01",
    label: "Politeness",
    pole: 7,
    angle: 216,
    simpleDefinition: "Having good manners and being respectful toward other people.",
    studentDefinition: "Using \"please\" and \"thank you\" and treating people with kindness, even when you're frustrated.",
    status: 'unseen',
    elo: 1200,
    wins: [],
    losses: []
  },
  {
    id: "obe-01",
    label: "Obedience",
    pole: 7,
    angle: 216,
    simpleDefinition: "Following the rules or doing what you are asked to do by people in charge.",
    studentDefinition: "Doing what your teachers or parents ask you to do because you respect the rules.",
    status: 'unseen',
    elo: 1200,
    wins: [],
    losses: []
  },
  {
    id: "res-01",
    label: "Restraint",
    pole: 7,
    angle: 216,
    simpleDefinition: "Keeping your impulses and emotions under control.",
    studentDefinition: "Being able to stop yourself from saying something mean or doing something silly in the middle of class.",
    status: 'unseen',
    elo: 1200,
    wins: [],
    losses: []
  },
  {
    id: "com-02",
    label: "Compliance",
    pole: 7,
    angle: 216,
    simpleDefinition: "Following a specific set of standards, rules, or laws.",
    studentDefinition: "Making sure you follow the guidelines for a project or the rules of a game exactly as they are written.",
    status: 'unseen',
    elo: 1200,
    wins: [],
    losses: []
  },
  {
    id: "sha-01",
    label: "Social Harmony",
    pole: 7,
    angle: 216,
    simpleDefinition: "Acting in a way that avoids arguments and helps everyone get along.",
    studentDefinition: "Being the person who helps keep the peace and makes sure everyone in the group is happy.",
    status: 'unseen',
    elo: 1200,
    wins: [],
    losses: []
  },
  {
    id: "roo-01",
    label: "Roots",
    pole: 8,
    angle: 252,
    simpleDefinition: "Feeling a strong connection to your family history and where you come from.",
    studentDefinition: "Knowing your family’s story and feeling proud of the place and culture you grew up in.",
    status: 'unseen',
    elo: 1200,
    wins: [],
    losses: []
  },
  {
    id: "hum-01",
    label: "Humility",
    pole: 8,
    angle: 252,
    simpleDefinition: "Being modest about your achievements and not acting like you are better than others.",
    studentDefinition: "Being a \"quiet winner\" who doesn't brag or show off when they do something great.",
    status: 'unseen',
    elo: 1200,
    wins: [],
    losses: []
  },
  {
    id: "dev-01",
    label: "Devotion",
    pole: 8,
    angle: 252,
    simpleDefinition: "Being very loyal and committed to a person, a cause, or a belief.",
    studentDefinition: "Being 100% dedicated to something you believe in, like a team, a hobby, or a cause.",
    status: 'unseen',
    elo: 1200,
    wins: [],
    losses: []
  },
  {
    id: "mod-01",
    label: "Moderation",
    pole: 8,
    angle: 252,
    simpleDefinition: "Avoiding extremes and keeping things in a healthy balance.",
    studentDefinition: "Finding the \"middle ground\"—like playing games for a bit, then studying, then sleeping.",
    status: 'unseen',
    elo: 1200,
    wins: [],
    losses: []
  },
  {
    id: "cub-01",
    label: "Cultural Belonging",
    pole: 8,
    angle: 252,
    simpleDefinition: "Feeling like you are part of a specific group, community, or heritage.",
    studentDefinition: "Feeling like you truly \"fit in\" with your community and celebrate the same traditions.",
    status: 'unseen',
    elo: 1200,
    wins: [],
    losses: []
  },
  {
    id: "rfh-01",
    label: "Respect for History",
    pole: 8,
    angle: 252,
    simpleDefinition: "Valuing the lessons, stories, and people from the past.",
    studentDefinition: "Appreciating the things that happened before you were born and learning from those stories.",
    status: 'unseen',
    elo: 1200,
    wins: [],
    losses: []
  },
  {
    id: "fam-02",
    label: "Family",
    pole: 9,
    angle: 288,
    simpleDefinition: "Prioritizing the bonds and wellbeing of your immediate relatives.",
    studentDefinition: "Putting your family first and making sure you spend time supporting and loving them.",
    status: 'unseen',
    elo: 1200,
    wins: [],
    losses: []
  },
  {
    id: "fri-01",
    label: "Friendship",
    pole: 9,
    angle: 288,
    simpleDefinition: "Valuing deep, supportive, and fun connections with your peers.",
    studentDefinition: "Being a great friend and making sure your squad knows you’re always there for them.",
    status: 'unseen',
    elo: 1200,
    wins: [],
    losses: []
  },
  {
    id: "loy-01",
    label: "Loyalty",
    pole: 9,
    angle: 288,
    simpleDefinition: "Staying faithful and supportive to your friends, family, or group.",
    studentDefinition: "Having someone's back no matter what, especially when things get difficult for them.",
    status: 'unseen',
    elo: 1200,
    wins: [],
    losses: []
  },
  {
    id: "hon-01",
    label: "Honesty",
    pole: 9,
    angle: 288,
    simpleDefinition: "Being truthful and sincere in everything you say and do.",
    studentDefinition: "Being the person who tells the truth, even when it’s hard or when you might get in trouble.",
    status: 'unseen',
    elo: 1200,
    wins: [],
    losses: []
  },
  {
    id: "for-01",
    label: "Forgiveness",
    pole: 9,
    angle: 288,
    simpleDefinition: "Choosing to let go of anger toward someone who has upset you.",
    studentDefinition: "Deciding not to stay mad at a friend who made a mistake, and moving on together.",
    status: 'unseen',
    elo: 1200,
    wins: [],
    losses: []
  },
  {
    id: "res-02",
    label: "Responsibility",
    pole: 9,
    angle: 288,
    simpleDefinition: "Taking ownership of your tasks and the results of your actions.",
    studentDefinition: "Stepping up and doing what you’re supposed to do without being nagged by an adult.",
    status: 'unseen',
    elo: 1200,
    wins: [],
    losses: []
  },
  {
    id: "sju-01",
    label: "Social Justice",
    pole: 10,
    angle: 324,
    simpleDefinition: "Working toward a world where everyone is treated fairly and has equal rights.",
    studentDefinition: "Standing up for people who are being treated unfairly and wanting everyone to have a fair shot.",
    status: 'unseen',
    elo: 1200,
    wins: [],
    losses: []
  },
  {
    id: "equ-01",
    label: "Equality",
    pole: 10,
    angle: 324,
    simpleDefinition: "Believing that every person deserves the same rights, status, and opportunities.",
    studentDefinition: "Treating everyone the same, no matter who they are, where they’re from, or what they look like.",
    status: 'unseen',
    elo: 1200,
    wins: [],
    losses: []
  },
  {
    id: "tol-01",
    label: "Tolerance",
    pole: 10,
    angle: 324,
    simpleDefinition: "Accepting and respecting beliefs or behaviors that are different from your own.",
    studentDefinition: "Being cool with people who have different opinions, religions, or lifestyles than you do.",
    status: 'unseen',
    elo: 1200,
    wins: [],
    losses: []
  },
  {
    id: "pom-01",
    label: "Peace of Mind",
    pole: 10,
    angle: 324,
    simpleDefinition: "Having a feeling of internal calm and freedom from worry.",
    studentDefinition: "That quiet, calm feeling inside where you aren't stressed out about drama or problems.",
    status: 'unseen',
    elo: 1200,
    wins: [],
    losses: []
  },
  {
    id: "ste-01",
    label: "Stewardship",
    pole: 10,
    angle: 324,
    simpleDefinition: "Taking care of the environment and the world around you for the future.",
    studentDefinition: "Doing your part to protect the planet, like recycling or making sure you don't waste resources.",
    status: 'unseen',
    elo: 1200,
    wins: [],
    losses: []
  },
  {
    id: "wis-01",
    label: "Wisdom",
    pole: 10,
    angle: 324,
    simpleDefinition: "Using your experience and knowledge to make good, balanced decisions.",
    studentDefinition: "Using what you’ve learned in life to make smart choices that help you and others in the long run.",
    status: 'unseen',
    elo: 1200,
    wins: [],
    losses: []
  }
];
